Length=54 #number of tiles
Turns=50 #Number of turns
Desert=14 #Number of desert tiles after >0 mountain tiles
Water=4 #N+WIDTH OF OCEAN (ie. OCEANWIDTH*2+1) tiles of hydrated terrain after ocean
OCEANWIDTH=4 #Number of tiles to the side of the centre that an ocean expands
MOUNTAINWIDTH=2 #As above but mountains
TERRAINWIDTH=6 #Width of Forest AND Swamp (2*TW+1, W either side of Loc)
SHOW_WORLD_BETWEEN_GIANTS=0 #1 to show world between each move. Probably slower.
SL=0.11 #Thickness of layer of terrain colour, depth below ground level of sea level